config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"

   #items
  get "/my_items", to: "items#my_items", as: :my_items
  # users
  get "users/:id/dashboard", to: "users#dashboard", as: :dashboard

  # bookings
  get "items/:id/bookings/new", to: "bookings#new", as: :new_booking
  post "items/:id/bookings", to: "bookings#create", as: :bookings
  resources :bookings, only: [:destroy]

  # items
  get 'search', to: 'items#search', as: :search
  resources :items, only: [:index, :show, :new, :destroy, :create]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one :review
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  validates :name, :description, :price_per_day, :location, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :score, inclusion: { in: (0..5) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :items, dependent: :destroy

  validates :first_name, :last_name, :email, :password, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: :new

  def new
    @booking = Booking.new(@item)
    @item = Item.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    date = params[:booking][:start_date]
    all_dates = date.split(" to ")
    @booking.start_date = all_dates[0]
    @booking.end_date = all_dates[1]
    @booking.user = current_user
    @booking.item = Item.find(params[:id])

    @booking.save
    redirect_to dashboard_path(current_user)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path(@booking.user), status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:price)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: :create

  def index
    @items = Item.all
    if params[:item_name].present?
      @items = @items.where("name ILIKE :item_name OR description ILIKE :item_name", item_name: "%#{params[:item_name]}%")
    end

    location = params[:item_location]
    if params[:item_location].present?
      @items = @items.near(location, 200)
    end

    # if params[:item_location] && params[:item_location] != ""
    #   @items = @items.where(params[:item_location])
    # end

    # if params[:item_dates] && params[:item_dates] != ""
    #   @items = @items.where(params[:item_dates])
    # end
  end

  def search
    @bg_red = true
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
    @bg_blue = true
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    @item.save
    redirect_to items_path
  end

  def my_items
    @items = current_user.items
    @user = current_user
    #get all the items from the current user
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to my_items_path, status: :see_other
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :location, :price_per_day, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @bg_blue = true
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :dashboard
  
  def index
    @users = User.all
  end

  def dashboard
    @user = User.find(params[:id])
    @bookings = Booking.where(user: @user)
    @items = @user.items # same as where method above

    # @rented_items = @user.is_owner?.includes(:item)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_bg_colour
    if @bg_red
      'bg-red'
    elsif @bg_blue
      'bg-blue'
    elsif params[:controller].match?(/devise/)
      'bg-orange'
    end
  end
end

app/views/bookings/new.html.erb
<div class= "container-new-booking">
 <div class="your-booking">
    <h1>Your booking</h1>
  </div>
  <div class="reservation">
    <div class="your-item">
      <p>Item:</p>
      <h2><%= @item.name %></h2>
    </div>

    <div class="dates">
      <div>
        <p>Choose your dates:</p>
        <%=form_with model: @booking do |f| %>
          <div data-controller="price-calculator" data-price-calculator-price-value="<%= @item.price_per_day %>">
            <%= f.text_field :start_date,
                        as: :string,
                        data: {controller: "calendar", action:"input->price-calculator#count", price_calculator_target:"input"},
                      class:"form-control", placeholder:"Select dates..."%>
            <%= f.hidden_field :price, data: { price_calculator_target: 'priceField' } %>
            <p>Total for <span data-price-calculator-target="days">-</span> days:</p>
            <p class="total"><strong data-price-calculator-target="total" >- </strong> €</p>
          </div>
          <%= f.submit "Confirm my booking", class:"confirm"  %>
        <%end%>
      </div>
    </div>

  </div>
  <%= link_to "Sign in", new_user_session_path, class: "button-simple fs-6" %>
</div>

app/views/items/index.html.erb
<section class="search-section">
  <%= link_to search_path do %>
      <i class="bi bi-search search-i"></i>
      <div>
        <p id="item-name"><strong><%= params[:item_name]&.capitalize %></strong></p><br>
        <p id="item-info"><%= params[:item_location]&.capitalize %> · <%=  params[:item_dates]&.capitalize %></p>
      </div>
  <% end %>
</section>

<section class="items-list">
  <ul>
    <% @items.each do |item| %>
      <%= link_to item_path(item) do %>
        <li class="items-li">
          <%#<%= image_tag(item.image_url, alt: 'cat skipping a rope') %>
          <%= cl_image_tag(item.photo.key, alt: item.description) %>
          <div class="flex-items">
            <div class="left-text">
              <h4 class="item-name"><%= item.name %></h4>
              <p><%= item.description.truncate(50) %></p>
              <p style="color: #797979;"><%= item.location %></p>
            </div>
            <h5><%= item.price_per_day %>€</h5>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</section>

app/views/items/my_items.html.erb
<section class="listed-items">
<h1 class="header">My items</h1>
<%# how can I interate over the items and display the items %>
<%# items.any? if contains item returns true//
<%#items.each = interating over the array %>
<div class="space-between-container" style="width: 360px;">
  <h4 class="align-self-center" style="margin-left: 16px;"><%= @user.first_name.capitalize + " " + @user.last_name.capitalize %></h4>
  <%= link_to new_item_path do %>
    <div class="button-important smaller-p">Add item</div>
  <% end %>
</div>

<% if @items.any? %>
  <ul>
    <% @items.each do |item| %>
      <%= link_to item_path(item) do %>
        <li class="items-li" style= "width: 90%; padding: 13px; margin-bottom: 18px;">
          <div class="flex-items">
            <div class="left-text">
              <h4 style="margin: 4px 0 4px 8px;"> <%= item.name %></h4>
              <p><%= item.price_per_day %>€ per day</p>
            </div>
            <div>
              <%= link_to '#' do %>
                <p class="button-simple smaller-p" style="margin-top: 0px; padding: 8px 14px;">Edit</p>
              <% end %>
              <%= link_to item_path(item), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
                <p class="button-simple smaller-p" style="margin-top: 4px; padding: 8px 14px;">Delete</p>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
  <% else %>
    <p class="border-horizontal"> No items </p>
  <% end %>
</section>

<section>
    <%= link_to dashboard_path(current_user) do %>
      <p class="button-important smaller-p" style="width: 160px; margin: 0 auto;">My bookings</p>
    <% end %>
</section>

<%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
  <p class="logout"><strong>Log out</strong></p>
<% end %>

app/views/items/new.html.erb
<h1 class="header">List an item</h1>
<%= form_with model: @item do |f| %>
  <%= f.text_field :name, placeholder: "What is it?", class: "input" %><br>
  <%= f.text_area :description, placeholder: "Please describe it", class: "input" %><br>
  <%= f.text_field :location, placeholder: "Location", class: "input" %><br>
  <%= f.file_field :photo %>
  <p style="margin-top: 20px;"><strong>Price per day</strong></p>
  <div class="space-between-container">
    <p>5€</p><p>100€</p>
  </div>
  <%= f.range_field :price_per_day, in: 5..100, class: "scroll" %><br>
  <%= f.submit "Add item", class: "button-important", id: "add" %>
<% end %>

app/views/items/search.html.erb
<h2 id="title-text">Start the<br>adventure...</h2>
<%= form_tag "/items", method: 'get' do |i| %>
  <%= text_field_tag :item_name, params[:item_name], placeholder: "I need...", class: "input" %><br>
  <%= text_field_tag :item_location, params[:item_location], placeholder: "Where?", class: "input" %><br>
  <p style="margin-top: 20px; color: white;">From</p>
  <%= date_field_tag :item_dates, params[:item_dates], placeholder: "When?", class: "input" %><br>
  <%= submit_tag "Search", class: "button-important smaller-p", id: "search" %>
<% end %>

app/views/items/show.html.erb
<div id="items-carousel" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#items-carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#items-carousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#items-carousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= cl_image_tag(@item.photo.key)%>
    </div>
    <div class="carousel-item">
      <%= cl_image_tag(@item.photo.key)%>
    </div>
    <div class="carousel-item">
      <%= cl_image_tag(@item.photo.key)%>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#items-carousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#items-carousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div class ="container-show">
  <div class="item">
    <h1 class= "title"><%= @item.name %></h1>
    <p class="category"><strong>Category:</strong> <%= @item.category %></p>
    <p style="color: #797979;" class="left-text" style="margin-bottom: 16px;"><%= @item.location %></p>
    <p><%= @item.description %></p>
  </div>

  <div class="price-rating">
    <p class="price"><strong><%= @item.price_per_day %> €</strong>/day</p>
    <p class="rating"><strong>4.98*</strong></p>
  </div>
  <div class="more-info">
    <p><%= @item.description %></p>
    <%# <p>More info here : Nuestro equipo de skaters ha desarrollado este pequeño skateboard para los niños que quieren comenzar a pasearse en skateboard.Esta tabla es una forma lúdica para empezar a desplazarse y a patinar.</p> %>
  </div>

  <%# <div class="reviews">
    <p><strong>Reviews</strong></p>
    <div>
      <p>user.first_name</p>
      <p>user.comment</p>
      <p>user.score</p>
    </div> %>
  </div>
</div>

<footer >
    <div class="total-price">
      <p><strong><%= @item.price_per_day %>€</strong> total </p>
      <p>Free cancelation</p>
    </div>
    <div><button type="button"
    class="book"><%=link_to "Book", new_booking_path(@item), class:"text-white" %></button></div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdventureExchange</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="<%= body_bg_colour %>" style="margin-top: 68px;">
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1 id="main-headline">Adventure Exchange</h1>
<%= link_to search_path do %>
  <p class="button-simple explore">Explore</p>
<% end %>
<%# <h1 id="moving-headline">Adventure Exchange</h1> %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to search_path do %>
    <i class="bi bi-search search-i"></i>
  <% end %>
  <% if current_user %>
    <%= link_to dashboard_path(current_user) do %>
      <i class="bi bi-person"></i>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path do %>
      <i class="bi bi-person"></i>
    <% end %>
  <% end %>
</div>

app/views/users/dashboard.html.erb
<h1 class="header">My bookings</h2>

<h4 class="align-self-center" style="margin-left: 16px;"><%= @user.first_name + " " + @user.last_name %></h4>

<section class="items-list">
  <% if @bookings.any? %>
    <ul>
      <% @bookings.each do |booking| %>
        <%= link_to item_path(booking.item_id) do %>
          <li class="items-li">
            <div class="flex-items">
              <div class="left-text" style="margin: 8px 0 0 8px;">
                <h4 class="item-name" style="margin-top: -12px;"><%= booking.item.name %></h4>
                <p class="smaller-p" style="margin-top: -4px;"><%= booking.start_date.strftime('%e %B') %> to<br><%= booking.end_date.strftime('%e %B %y') %></p>
              </div>
              <div>
                <%= link_to '#' do %>
                  <p class="button-simple smaller-p" style="margin-top: 0px;">Edit</p>
                <% end %>
                <%= link_to booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
                  <p class="button-simple smaller-p" style="margin-top: 4px;">Delete</p>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  <% else %>
    <p class="border-horizontal">You don't have any bookings yet.</p>
  <% end %>
</section>

<section>
    <%= link_to my_items_path do %>
      <p class="button-important smaller-p" style="width: 120px; margin: 0 auto;">My items</p>
    <% end %>
</section>

<%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
  <p class="logout"><strong>Log out</strong></p>
<% end %>